title: Hi! I'm Liz
description: > 
  Alpaca's Dev Blog.
permalink: ':title/'
baseurl: "/" 
url: "missalpaca.github.io/" 
imgrul: 'http://missalpaca.github.io/assets/img/'

# Author Settings
author: Lizeth Garcia # add your name
author-img: lizeth-garcia.jpg # add your photo
about-author: I am a web designer # add description
social-twitter: lizethgarciar # add your Twitter handle
social-github: missalpaca # add your Github handle
social-linkedin: kazegarcia # add your Linkedin handle
social-email: kazegarciar@gmail.com # add your Email address

# Disqus
discus-identifier: missalpaca # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
